---
# Python logging configuration file.
# Configures settings for loggers.
# More:
# https://docs.djangoproject.com/en/1.10/topics/logging/
# https://www.caktusgroup.com/blog/2015/01/27/Django-Logging-Configuration-logging_config-default-settings-logger/


version: 1
disable_existing_loggers: False


formatters:
  simple:
    format: "%(asctime)s - %(levelname)-8s - %(name)-12s - %(funcName)s: %(message)s"
  plain:
    format: "%(asctime)s - %(levelname)s <%(funcName)s> %(message)s"


handlers:
  console:
    class: "logging.StreamHandler"
    formatter: plain
    level: INFO
    stream: "ext://sys.stdout"

  debug_file_handler:
    class: "logging.handlers.RotatingFileHandler"
    formatter: plain
    filename: "debug.log"
    level: DEBUG
    maxBytes: 10485760  # 10 MB
    backupCount: 20
    encoding: "utf8"

  info_file_handler:
    class: "logging.handlers.RotatingFileHandler"
    formatter: plain
    filename: "info.log"
    level: INFO
    maxBytes: 10485760  # 10 MB
    backupCount: 20
    encoding: "utf8"


loggers:
  gamestore.views:
    level: INFO
    handlers: [console, debug_file_handler, info_file_handler]
    propagate: no


root:
  level: INFO
  handlers: [console]

...