# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 20:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.ImageField(height_field=48, upload_to='games', verbose_name='', width_field=48),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to='games', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, 'Value must be positive.')], verbose_name='Price for the game. Value must be greater of equal to zero.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(upload_to='profile', verbose_name='Profile image.'),
        ),
    ]
