# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 09:29
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0002_auto_20161219_2035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
        migrations.AddField(
            model_name='score',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.ImageField(upload_to='games', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, 'Value must be positive.')], verbose_name='Price for the game. Value must be greater or equal to zero.'),
        ),
        migrations.AlterField(
            model_name='gamesale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Date when game was bought'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.PositiveIntegerField(verbose_name=''),
        ),
    ]
