# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 09:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0003_auto_20161223_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='Date when game was bought'),
        ),
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.utcnow, verbose_name=''),
        ),
    ]
