# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0009_auto_20170131_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('', ''), ('Male', ''), ('Female', '')], default='', max_length=140),
        ),
    ]
