# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0010_auto_20170207_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('other', 'Other'), ('male', 'Male'), ('female', 'Female')], default='', max_length=140),
        ),
    ]
