# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0012_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='accepted',
            field=models.BooleanField(default=None, verbose_name='Accepted/Rejected'),
        ),
    ]
