# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0013_application_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='/home/jaan/Projects/wsdproject/static/images/profile_default.png', null=True, upload_to='profiles', verbose_name='Profile picture.'),
        ),
    ]
