# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0014_auto_20170211_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles', verbose_name='Profile picture.'),
        ),
    ]
