# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0015_auto_20170211_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='games', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='games', verbose_name=''),
        ),
    ]
