# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0017_auto_20170211_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='games/image', verbose_name=''),
        ),
    ]
