# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0018_auto_20170211_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='accepted',
            field=models.NullBooleanField(default=None, verbose_name='NotProcesses/Accepted/Rejected'),
        ),
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='application',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Why you want to become a developer'),
        ),
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='games/icons', verbose_name='Game icon'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='games/image', verbose_name='Game image'),
        ),
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.URLField(verbose_name='Game url'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles', verbose_name='Profile picture'),
        ),
    ]
