# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0022_auto_20170217_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='developer_status',
            field=models.IntegerField(choices=[(0, 'basic_user'), (1, 'pending'), (2, 'confirmed')], default=0),
        ),
    ]
