# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 12:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0024_auto_20170218_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesale',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
